select
    {{ generate_surrogate_key(["outage_id"]) }} as outage_sk,
    outage_id,
    region,
    outage_type,
    severity,
    cast(outage_start_timestamp as timestamp) as outage_start_timestamp,
    cast(outage_end_timestamp as timestamp) as outage_end_timestamp,
    cast(duration_minutes as double) as duration_minutes,
    cast(affected_customers as bigint) as affected_customers,
    cast(resolved_flag as boolean) as resolved_flag,
    source_file_name,
    source_system,
    generated_at_utc,
    _source_file_path,
    _run_id,
    _environment,
    silver_processed_at_utc,
    {{ add_model_audit_columns() }}
from {{ source('silver', 'outage_events_clean') }}