select
    {{ generate_surrogate_key(["weather_id"]) }} as weather_sk,
    weather_id,
    cast(weather_date as date) as weather_date,
    region,
    cast(avg_temperature_c as double) as avg_temperature_c,
    cast(min_temperature_c as double) as min_temperature_c,
    cast(max_temperature_c as double) as max_temperature_c,
    cast(humidity_percent as double) as humidity_percent,
    cast(wind_speed_mph as double) as wind_speed_mph,
    weather_condition,
    cast(heating_degree_days as double) as heating_degree_days,
    cast(cooling_degree_days as double) as cooling_degree_days,
    source_file_name,
    source_system,
    generated_at_utc,
    _source_file_path,
    _run_id,
    _environment,
    silver_processed_at_utc,
    {{ add_model_audit_columns() }}
from {{ source('silver', 'weather_clean') }}