select
    {{ generate_surrogate_key(["billing_event_id"]) }} as billing_event_sk,
    billing_event_id,
    customer_id,
    tariff_id,
    region,
    cast(billing_date as date) as billing_date,
    cast(billing_period_start as date) as billing_period_start,
    cast(billing_period_end as date) as billing_period_end,
    cast(total_consumption_kwh as double) as total_consumption_kwh,
    cast(standing_charge_amount as double) as standing_charge_amount,
    cast(energy_charge_amount as double) as energy_charge_amount,
    cast(vat_amount as double) as vat_amount,
    cast(total_amount as double) as total_amount,
    payment_status,
    payment_method,
    cast(due_date as date) as due_date,
    cast(paid_at as date) as paid_at,
    cast(billing_quality_issue_injected as boolean) as billing_quality_issue_injected,
    source_file_name,
    source_system,
    generated_at_utc,
    _source_file_path,
    _run_id,
    _environment,
    silver_processed_at_utc,
    {{ add_model_audit_columns() }}
from {{ source('silver', 'billing_events_clean') }}