select
    {{ generate_surrogate_key(["reading_id"]) }} as meter_reading_sk,
    reading_id,
    meter_id,
    customer_id,
    cast(reading_timestamp as timestamp) as reading_timestamp,
    cast(reading_date as date) as reading_date,
    cast(consumption_kwh as double) as consumption_kwh,
    cast(voltage as double) as voltage,
    reading_source,
    meter_status,
    region,
    cast(is_late_arriving as boolean) as is_late_arriving,
    cast(ingestion_delay_hours as double) as ingestion_delay_hours,
    cast(data_quality_issue_injected as boolean) as data_quality_issue_injected,
    firmware_version,
    cast(signal_strength_dbm as double) as signal_strength_dbm,
    meter_reading_quality_code,
    source_file_name,
    source_system,
    generated_at_utc,
    _source_file_path,
    _run_id,
    _environment,
    silver_processed_at_utc,
    {{ add_model_audit_columns() }}
from {{ source('silver', 'meter_readings_clean') }}